---
title: "Maryland"
author: "Rob Wells, Hannah Marszalek"
date: "2023-10-18"
output: html_document
---
# Starter code for a quick analysis of Maryland news coverage and overall lynching data
```{r message=FALSE, warning=FALSE}
#install.packages("here")
here::here()
library(tidyverse)
library(tidyr)
#install.packages("ggmap")
library(ggmap)
library(googlesheets4)
#install.packages("geosphere")
library(geosphere)
#install.packages("janitor")
library(janitor)
library(lubridate)
library(kableExtra)
library(ggplot2)
```

## Creating and Cleaning Maryland Subset
```{r}
lynch_geocoded_10.8 <- read.csv("../data/lynch_geocoded_10.8.csv")

maryland <- lynch_geocoded_10.8 %>% 
  filter(state_lynch=="MD") 

#Cleaned city_lynch to fix issue with Queen Anne's County and with Bel Air
maryland <- maryland %>%
  mutate(city_lynch = ifelse(city_lynch %in% c("Queen annes county", "Queen Annes County", "Queen Annes County (eastern shore)"), "Queen Anne's County", city_lynch)) %>%
  mutate(city_lynch = str_replace(city_lynch, "Belair", "Bel Air"))

#Formatting date and adding month column
maryland <- maryland %>%
  mutate(date = mdy(date),
         month = floor_date(date, "month")) %>%
  select(newspaper_name:news_address, newspaper_city:year, city_lynch, state_lynch, lynching.lon:Newspaper_Region, month)
```

## Md Lynchings
```{r}
# Unused code
# x <- maryland %>% 
#   group_by(city_lynch, year) %>% 
#   filter(n()>1)
# 
# md_single_cases <- maryland %>% 
#     group_by(city_lynch, year) %>% 
#     distinct(lynch_address, .keep_all = TRUE)  
# 
# write.csv(md_single_cases, "../output/md_distinct_cases.csv")
# 
# zz <- md_single_cases %>% 
#   select(city_lynch, date, newspaper_name)


#Filtering to remove duplicates
distinct_md <- maryland %>%
  distinct(city_lynch, month, newspaper_name, .keep_all = TRUE)

md_cases_by_decade <- distinct_md %>%
  group_by(decade) %>% 
  count() %>% 
  rename(geocoded_count = n)

newspapers <- distinct_md %>%
  group_by(newspaper_name, newspaper_state_code) %>%
  count()

in_vs_out_of_state <- distinct_md %>%
  group_by(in_state) %>%
  count()
```

## Tolnay Md Analysis
```{r}
tolnay_beck <- read_csv("../data/Bailey_Beck_lynching_list_8_1_2022.csv") %>% 
  as.data.frame()

tolnay_beck <- janitor::clean_names(tolnay_beck)

tolnay_md <- tolnay_beck %>% 
  filter(lynch_state=="MD") %>% 
  select(name, year, month, day, status, lynch_county, place, method_of_death, accusation, mob_size, notes, decade) %>% 
  arrange(year)

#write.csv(tolnay_md, "../output/tolnay_md.csv")

tolnay_by_decade <- tolnay_md %>% 
  group_by(decade) %>% 
  count() %>%
  rename(tolnay_count = n)
```

## Combined Data Analysis
```{r}
# Comparison of numbers by decade
totals_by_decade <- left_join(md_cases_by_decade, tolnay_by_decade, by = "decade")

#Pulling only cases from Prince George's County
pg_county <- distinct_md %>%
  filter(city_lynch == "Prince George's County") %>%
  select(city_lynch, year)

tolnay_pg <- tolnay_md %>%
  select(year, lynch_county) %>%
  filter(lynch_county == "Prince George’s")

total_pg_county <- bind_rows(pg_county, tolnay_pg) %>%
  group_by(year) %>%
  count()
```

## Formatted Tables/Graphs
```{r}
#Creating tables for graph
count_tolnay <- tolnay_md %>%
  select(decade) %>%
  mutate(source = "Tolnay")

count_geocode <- distinct_md %>%
  select(decade) %>%
  mutate(source = "Our Data")

total_count <- bind_rows(count_tolnay, count_geocode) %>%
  group_by(decade, source) %>%
  count()

#RSW: Can you add numbers to the bars?
#Graph comparing our data and Tolnay's by decade
ggplot(total_count, aes(decade, n, fill = source)) +
  geom_bar(stat="identity", position = "dodge", width = 8) + 
  labs(title="Comparing Lynching Counts in Maryland Per Decade",
       x="Decade",
       y="Number of Reported Lynchings",
       fill = "Source")

```

```{r}
#Map of in state vs out of state coverage from our data
#Note: I haven't yet figured out why it is not including all the plot points (besides the ones with missing coordinates)
edited_distinct <- distinct_md %>%
  mutate(in_state = str_replace(in_state, "N", "Out-of-state"),
  in_state = str_replace(in_state, "Y", "In-state"))

md_map <- map_data("state", region = "maryland")

map_plot <- ggplot(data = md_map, aes(x = long, y = lat)) +
  geom_polygon(fill = "white", color = "black") +
  geom_point(data = edited_distinct, aes(x = lynching.lon, y = lynching.lat, color = in_state), size = 3) +
  scale_color_manual(values = c("Out-of-state" = "red", "In-state" = "blue")) +
  coord_quickmap() +
  theme_void() + 
  labs(title="Map of In-State vs. Out-of-State Coverage for Maryland Lynchings",
       color = "Newspaper Coverage") + 
  theme(axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank())

print(map_plot)
```
