---
title: "Mob Analysis_Jour389L version"
author: "Rob Wells"
date: "2023-11-15"
output: html_document
---
```{r message=FALSE, warning=FALSE}
#install.packages("here")
here::here()
library(tidyverse)
library(tidyr)
#install.packages("ggmap")
library(ggmap)
#register_google(key = "XXXX")
library(googlesheets4)
library(googledrive)
#install.packages("geosphere")
library(geosphere)
#install.packages("janitor")
library(stringr)
```

# Updates Nov. 15 with corrected data from Rachel McCrea
```{r}

googledrive::drive_auth()
# 
googlesheets4::gs4_deauth()

#mob <- read_sheet("https://docs.google.com/spreadsheets/d/1oKkRSInN8tO6Z-kyMoIUYOX1uHQhP7FdrR1xie4O-XQ/edit?usp=sharing")

#updates with Rachel McCrea's corrections
mob <- read_sheet("https://docs.google.com/spreadsheets/d/1-zwBtcpdH1Hnb5WROJVuPdm_HC9nTmDl-dbiSHE5tJ8/edit#gid=10206338")
```


```{r}

mob <- mob %>% 
  janitor::clean_names() 

#strip commas
mob <- mob %>% 
  mutate(code = str_replace_all(code, ","," ")) 

#new column, assign a 1 for any instance per row
mob <- mob %>%
  mutate(
    hostile = ifelse(grepl("\\bHostile\\b", code), 1, 0),
    neutral = ifelse(grepl("\\bNeutral\\b", code), 1, 0),
    orderly = ifelse(grepl("\\bOrderly\\b", code), 1, 0),
    justice = ifelse(grepl("\\bJustice\\b", code), 1, 0),
    identified = ifelse(grepl("\\bIdentified\\b", code), 1, 0),
    unsure = ifelse(grepl("\\bUnsure\\b", code), 1, 0),
    other = ifelse(grepl("\\bOther\\b", code), 1, 0)
  )
```

### Counting progress
```{r}
mob %>% 
  count(your_name) %>% 
  arrange(your_name)



```



#add decade, year
```{r}
mob <- mob %>% 
  mutate(date1 = lubridate::ymd(date)) %>% 
  mutate(year = lubridate::year(date1))



mob <- mob %>% 
    mutate(decade = case_when(
      year < 1800 ~ "pre1800",
      year >= 1800 & year <=1809 ~ "1800s",
      year >= 1810 & year <=1819 ~ "1810s",
      year >= 1820 & year <=1829 ~ "1820s",
      year >= 1830 & year <=1839 ~ "1830s",
      year >= 1840 & year <=1849 ~ "1840s",
      year >= 1850 & year <=1859 ~ "1850s",
      year >= 1860 & year <=1869 ~ "1860s",
      year >= 1870 & year <=1879 ~ "1870s",
      year >= 1880 & year <=1889 ~ "1880s",
      year >= 1890 & year <=1899 ~ "1890s",
      year >= 1900 & year <=1909 ~ "1900s",
      year >= 1910 & year <=1919 ~ "1910s",
      year >= 1920 & year <=1929 ~ "1920s",
      year >= 1930 & year <=1939 ~ "1930s",
      year >= 1940 & year <=1949 ~ "1940s",
      year >= 1950 & year <=1959 ~ "1950s",
      year >= 1960 & year <=1969 ~ "1960s",
      year >= 1970 ~ "post1970s"
         ))

```



```{r}
lynch_geocoded_10.8 <- read.csv("../data/lynch_geocoded_10.8.csv")


mob1 <- mob %>% 
  select(docname, newspaper, date, url, hostile, neutral, orderly, justice, identified, unsure, other) %>% 
  as.data.frame()

mob2 <- mob1 %>% 
  left_join(lynch_geocoded_10.8, by=c("docname"="file_id", "url"))

#write.csv(mob2, "../output/mob_full_11_15.csv")

mob2


mob3 <- mob2 %>% 
  group_by(decade) %>% 
  summarize(
    total_hostile = sum(hostile, na.rm = TRUE),
    total_neutral = sum(neutral, na.rm = TRUE),
    total_orderly = sum(orderly, na.rm = TRUE)
    ) %>% 
        mutate(
    grand_total = total_hostile + total_neutral + total_orderly,
    percent_hostile = total_hostile / grand_total * 100,
    percent_neutral = total_neutral / grand_total * 100,
    percent_orderly = total_orderly / grand_total * 100
  )

#write.csv(mob3, "../output/mob3_11_15.csv")


# Reshape the data
library(reshape2)
mob_melt <- melt(mob3, id.vars = "decade", 
                measure.vars = c("percent_hostile", "percent_neutral", "percent_orderly"))

write.csv(mob_melt, "../output/mob_melt_11_15.csv")

# Create the plot
ggplot(mob_melt, aes(x = decade, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Decade", y = "Percentage", fill = "Variable") +
  theme_minimal()
  

# mob2 <- mob2 %>% 
#   select(docname, newspaper_name, date.x, url, hostile, neutral, orderly, justice, identified, unsure, other, lynch_address, newspaper_state_code, year, city_lynch, state_lynch, miles, decade, Newspaper_Region, total_words)

#Apurva wrote this section -- updated

#I created a data frame that filtered for only Alabama, Mississippi, Georgia and Texas, and looked at columns with the total amounts of each categorization as well as the percentage of each mob categorization.

mob_state <- mob2 |>
  filter(
    str_detect(
      state_lynch, "AL|MS|GA|TX")) |>
  group_by(state_lynch) |>
  summarise(total_hostile = sum(hostile, na.rm = TRUE),
    total_neutral = sum(neutral, na.rm = TRUE),
    total_orderly = sum(orderly, na.rm = TRUE)) |>
    mutate(total = total_hostile + total_neutral + total_orderly,
    percent_hostile = total_hostile/total * 100,
    percent_neutral = total_neutral/total * 100,
    percent_orderly = total_orderly/total * 100) 

mob_state |>
  summarise(sum(total))

view(mob2)

#Created a separate data frame that filtered for all of the Northeast states to easily compare the results to the four Southern states. 

mob2 <- mob2 |> mutate(mob_region = case_when(state_lynch=="SC" ~ "South",
                            state_lynch=="TX" ~ "South",
                            state_lynch=="LA" ~ "South",
                            state_lynch=="TN" ~ "South",
                            state_lynch=="MS" ~ "South",
                            state_lynch=="AR" ~ "South",
                            state_lynch=="AL" ~ "South",
                            state_lynch=="GA" ~ "South",
                            state_lynch=="VA" ~ "South",
                            state_lynch=="FL" ~ "South",
                            state_lynch=="NC" ~ "South",
                            state_lynch=="MD" ~ "South",
                            state_lynch=="DE" ~ "South",
                            state_lynch=="WV" ~ "South",
                            state_lynch=="KY" ~ "South",
                            state_lynch=="MO" ~ "Midwest",
                            state_lynch=="ME" ~ "Northeast",
                            state_lynch=="NY" ~ "Northeast",
                            state_lynch=="NH" ~ "Northeast",
                            state_lynch=="VT" ~ "Northeast",
                            state_lynch=="MA" ~ "Northeast",
                            state_lynch=="CT" ~ "Northeast",
                            state_lynch=="RI" ~ "Northeast",
                            state_lynch=="PA" ~ "Northeast",
                            state_lynch=="NJ" ~ "Northeast",
                            state_lynch=="OH" ~ "Midwest",
                            state_lynch=="IN" ~ "Midwest",
                            state_lynch=="KS" ~ "Midwest",
                            state_lynch=="MI" ~ "Midwest",
                            state_lynch=="WI" ~ "Midwest",
                            state_lynch=="MN" ~ "Midwest",
                            state_lynch=="IO" ~ "Midwest",
                            state_lynch=="CA" ~ "West",
                            state_lynch=="NE" ~ "West",
                            state_lynch=="OR" ~ "West",
                            state_lynch=="IL" ~ "Midwest",
                            state_lynch=="NE" ~ "Midwest",
                            state_lynch=="CO" ~ "West",
                            state_lynch=="ND" ~ "Midwest",
                            state_lynch=="SD" ~ "Midwest",
                            state_lynch=="MO" ~ "West",
                            state_lynch=="WA" ~ "West",
                            state_lynch=="ID" ~ "West",
                            state_lynch=="WY" ~ "West",
                            state_lynch=="UT" ~ "West",
                            state_lynch=="OK" ~ "South",
                            state_lynch=="NM" ~ "West",
                            state_lynch=="AZ" ~ "West",
                            state_lynch=="AL" ~ "West",
                            state_lynch=="HI" ~ "West",
                            state_lynch=="DC" ~ "South",
                            state_lynch=="VI" ~ "Misc",
                                                     TRUE~mob_region))

mob_northeast <- mob2 |>
  filter(mob_region == 'Northeast') |>
    group_by(state_lynch) |>
    summarise(
      total_hostile = sum(hostile, na.rm = TRUE),
      total_neutral = sum(neutral, na.rm = TRUE),
      total_orderly = sum(orderly, na.rm = TRUE)) |>
    mutate(total = total_hostile + total_neutral + total_orderly,
      percent_hostile = total_hostile/total * 100,
      percent_neutral = total_neutral/total * 100,
      percent_orderly = total_orderly/total * 100) 

mob_northeast |>
  summarise(sum(total))
  
#Charts Hostile, Neutral, Orderly Percentages for Alabama, Georgia, Mississippi and Texas.

library(reshape2)

mob_state_melt <- melt(mob_state, id.vars = "state_lynch", 
                measure.vars = c("percent_hostile", "percent_neutral", "percent_orderly"))


write.csv(mob_state_melt, "../output/mob_state_melt.csv")

ggplot(mob_state_melt, aes(x = state_lynch, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "State", y = "Percentage", fill = "Variable") +
  theme_minimal()


#Hostile, Neutral, Orderly Percentages for Northeast states: CT, ME, NJ, NY and PA.

mob_northeast_melt <- melt(mob_northeast, id.vars = "state_lynch", 
                measure.vars = c("percent_hostile", "percent_neutral", "percent_orderly"))


write.csv(mob_state_melt, "../output/mob_northeast_melt.csv")

ggplot(mob_northeast_melt, aes(x = state_lynch, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "State", y = "Percentage", fill = "Variable") +
  theme_minimal()


  


```

